Hospital-Management-System-By-Ibrahim/HMSproject/Controllers/SearchController.cs
using HMSproject.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis;
using Microsoft.EntityFrameworkCore;

namespace HMSproject.Controllers


{
    public class SearchController : Controller
    {


        public SearchController(HmsContext db)
        {
            _db = db;
        }

        private readonly HmsContext _db;




        /*-------------------------------------------------------------------------*/
        public IActionResult Spatient(string? nid)
        {
            if (nid == null)
            {
                var patients = _db.AspNetUsers
                    .Include(p => p.Appointments)
                    .ToList();

                return View(patients);
            }
            else
            {
                var patient = _db.AspNetUsers
                    .Include(p => p.Appointments)
                    .FirstOrDefault(p => p.SSN == nid);

                if (patient == null)
                {
                    return NotFound("No Patient");
                }

                return View(new List<Patient> { patient });
            }
        }









        /*-------------------------------------------------------------------------*/

        public IActionResult Shictory(string? Id)
        {
            if (Id == null)
            {
                return NotFound("Not Found");
            }


            var patient = _db.AspNetUsers.Find(Id);
            var appointment = _db.Appointments.FirstOrDefault(a => a.PatientID == patient.Id);

      

            var diagnosis = _db.Diagnose.Where(d => d.fk_app == appointment.Id).ToList();

        
           
            return View(diagnosis);
        }








        /*-------------------------------------------------------------------------*/




        //public IActionResult edit(string? Id)
        //{
        //    // Get the current patient
        //    var patient = _db.AspNetUsers.Find(Id);

        //    // Get the current prescription for the patient
        //    var appointment = _db.Appointments.FirstOrDefault(g => g.PatientID==  patient.Id);
        //    var diagnosis = _db.Diagnoses.Where(d => d.FkApp == appointment.Id).ToList();

        //    // Pass the prescription data to the view
        //    return View(diagnosis);
        //}



        ////Post
        //[HttpPost]
        //[ValidateAntiForgeryToken]


        //public IActionResult edit(Diagnose model)
        //{
        //    // Get the diagnosis from the database
        //    var diagnosis = _db.Diagnoses.Find(model.Id);
        //    if (diagnosis != null)
        //    {

        //        // Update the diagnosis with the new data
        //        diagnosis.Prescription = model.Prescription;
        //        diagnosis.Description = model.Description;
        //        diagnosis.Analysis = model.Analysis;
        //        diagnosis.FkApp = model.FkApp;

        //        _db.SaveChanges();

        //        // Redirect to the Hictory page
        //        var appointment = _db.Appointments.FirstOrDefault(a => a.Id == diagnosis.FkApp);
        //        return RedirectToAction("Hictory", new { id = appointment.PatientID });
        //    }
        //    else { return NotFound("Not found"); }

        //}

        public IActionResult Edit(int? id)
        {
            var diagnosis = _db.Diagnose.Find(id);
            if (diagnosis == null)
            {
                return NotFound();
            }

            return View(diagnosis);
        }

        [HttpPost]
        public IActionResult Edit(int id, Diagnose model)
        {
            var diagnosis = _db.Diagnose.Find(id);
            if (diagnosis == null)
            {
                return NotFound();
            }

            diagnosis.Prescription = model.Prescription;
            diagnosis.Description = model.Description;
            diagnosis.Analysis = model.Analysis;

            _db.SaveChanges();
            TempData["sure"] = "The Data has been updated successfully";

            return RedirectToAction("Spatient");
        }



        /*-------------------------------------------------------------------------*/


        public IActionResult Delete(int? Id)
        {
            if (Id == null )
            {
                return NotFound();
            }
            var del = _db.Diagnose.Find(Id);
            if (del == null)
            {
                return NotFound();
            }
            return View(del);
        }



        //Post
        [HttpPost]

        public IActionResult Delete(Diagnose k,string? Id)
        {

            _db.Diagnose.Remove(k);
            _db.SaveChanges();
            TempData["sure"] = "The Data has been delete successfully";
            return RedirectToAction("Spatient");
            
          
        }






    }
}

Hospital-Management-System-By-Ibrahim/HMSproject/Views/Search/delete.cshtml
@using HMSproject.Models;
@model Diagnose




@{
    ViewData["Title"] = "Delete";
    Layout = "_LayoutDoctor";
}
    <style>


    
        .bg-1 {
            background-image: url("../Doctor/Images/22.jpg");
            background-size: cover;
            position: relative;
        }
    


        select {
            /* Reset Select */
            appearance: none;
            outline: 0;
            border: 0;
            box-shadow: none;
            /* Personalize */
            flex: 1;
            padding: 0 1em;
            color: #fff;
            background-color: var(--darkgray);
            background-image: none;
            cursor: pointer;
        }
            /* Remove IE arrow */
            select::-ms-expand {
                display: none;
            }
        /* Custom Select wrapper */
        .select {
            position: relative;
            display: flex;
            width: 20em;
            height: 3em;
            border-radius: .25em;
            overflow: hidden;
        }
            /* Arrow */
            .select::after {
                content: '\25BC';
                position: absolute;
                top: 0;
                right: 0;
                padding: 1em;
                background-color: black;
                transition: .25s all ease;
                pointer-events: none;
            }
            /* Transition */
            .select:hover::after {
                color: white;
            }

        /* Other styles*/
        body {
            color: #fff;
        }

        h1 {
            margin: 0 0 0.25em;
        }

        a {
            font-weight: bold;
            color: var(--gray);
            text-decoration: none;
            padding: .25em;
            border-radius: .25em;
            background: white;
        }
    </style>

    <!-- ************************************************************************************************************ -->

    <section class="page-title bg-1">
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="block text-center">
                        <span class="text-white"></span>
                        <h1 class="text-capitalize mb-5 text-lg">prescription</h1>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- ****************************************Medical History****************************************************** -->
    <section class="section doctor-qualification gray-bg">
        <div class="container">
            <div class="section-title">
                <h3>Doctor Tips</h3>
                <div class="divider my-4"></div>
            </div>

            <form method="post" asp-action="Delete" asp-controller="Search">
                <!-- Textarea 2 rows height -->
                <div class="form-outline">
                    <label asp-for="Description" style="color: black;" class="form-label" for="textAreaExample3">Description </label>
                    <textarea asp-for="Description" disabled class="form-control" id="textAreaExample3" rows="6" placeholder="Write The Patient State" required placeholder="Prescription" style="background-color:whitesmoke ; color: black;"></textarea>
                    
                </div>
                <br>
                <hr />



                <div class="form-outline">
                    <label asp-for="Prescription" style="color: black;" class="form-label" for="textAreaExample2">prescription</label>
                    <textarea asp-for="Prescription" disabled class="form-control" id="textAreaExample2" rows="6" placeholder="Write The prescription" required placeholder="Prescription" style="background-color:whitesmoke ; color: black;"></textarea>
                    
                </div>
                <br>

                <!-- Textarea without sizing class -->
                <p style="color: black; font-size: medium;">Choose The Medical Analysis</p>
                <div class="select">
                    <select style="background-color:black" asp-for="Analysis" disabled>
                        <option value="No Thing">No Thing</option>
                        <option value="CBC">CBC</option>
                        <option value="ESR">ESR</option>
                        <option value="APTT">APTT</option>
                        <option value="Urea">Urea</option>


                    </select>
                   

                </div>

                <button class="btn btn-slide-9" type="submit" style="background-color:black; margin-left: 50%; color: white; ">Delete</button>
            </form>

        </div>
    </section>

    <hr />
    <!-- ************************************************************************************************************* -->
    <a class="btn btn-slide-9" asp-controller="Search" asp-action="shictory" type="submit" style="background-color:black; margin-left: 85%; margin-top: 10%; color: white; ">Back &nbsp; <i style="color:white; margin:auto;" class="bi bi-arrow-bar-right"></i> </a>

@section Scripts
    {
    <partial name="_ValidationScriptsPartial.cshtml" />
}

Hospital-Management-System-By-Ibrahim/HMSproject/Views/Search/edit.cshtml
@using HMSproject.Models;
@model Diagnose


@{
    ViewData["Title"] = "Edit";
    Layout = "_LayoutDoctor";
}
    <style>


        .bg-1 {
            background-image: url("../Doctor/Images/22.jpg");
            background-size: cover;
            position: relative;
        }



        select {
            /* Reset Select */
            appearance: none;
            outline: 0;
            border: 0;
            box-shadow: none;
            /* Personalize */
            flex: 1;
            padding: 0 1em;
            color: #fff;
            background-color: var(--darkgray);
            background-image: none;
            cursor: pointer;
        }
            /* Remove IE arrow */
            select::-ms-expand {
                display: none;
            }
        /* Custom Select wrapper */
        .select {
            position: relative;
            display: flex;
            width: 20em;
            height: 3em;
            border-radius: .25em;
            overflow: hidden;
        }
            /* Arrow */
            .select::after {
                content: '\25BC';
                position: absolute;
                top: 0;
                right: 0;
                padding: 1em;
                background-color: black;
                transition: .25s all ease;
                pointer-events: none;
            }
            /* Transition */
            .select:hover::after {
                color: white;
            }

        /* Other styles*/
        body {
            color: #fff;
        }

        h1 {
            margin: 0 0 0.25em;
        }

        a {
            font-weight: bold;
            color: var(--gray);
            text-decoration: none;
            padding: .25em;
            border-radius: .25em;
            background: white;
        }
    </style>
    <!-- ************************************************************************************************************ -->

    <section class="page-title bg-1">
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="block text-center">
                        <span class="text-white"></span>
                        <h1 class="text-capitalize mb-5 text-lg">prescription</h1>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- ****************************************Medical History****************************************************** -->
    <section class="section doctor-qualification gray-bg">
        <div class="container">
            <div class="section-title">
                <h3>Doctor Tips</h3>
                <div class="divider my-4"></div>
            </div>

            <form method="post" asp-action="Edit" asp-controller="Search">

                <!-- Textarea 2 rows height -->
                <div class="form-outline">

                    <label style="color: black;" class="form-label" for="textAreaExample3">Description </label>
                    <textarea asp-for="Description" class="form-control" id="textAreaExample3" rows="6" placeholder="Write The Patient State" required placeholder="Description" style="background-color:whitesmoke ; color: black;"></textarea>
                    <span asp-validation-for="Description" style=" font-size:medium;"></span>
                </div>
                <br>
                <hr />



                <div class="form-outline">


                    <label asp-for="Prescription" style="color: black;" class="form-label" for="textAreaExample2">prescription</label>
                    <textarea asp-for="Prescription" class="form-control" id="textAreaExample2" rows="6" placeholder="Write The prescription" required placeholder="Prescription" style="background-color:whitesmoke ; color: black;"></textarea>
                    <span asp-validation-for="Prescription" style=" font-size:medium;"></span>
                </div>
                <br>

                <!-- Textarea without sizing class -->
                <p style="color: black; font-size: medium;">Choose The Medical Analysis</p>
                <div class="select">
                    <select style="background-color:black" asp-for="Analysis">
                        <option value="No Thing">No Thing</option>
                        <option value="CBC">CBC</option>
                        <option value="ESR">ESR</option>
                        <option value="APTT">APTT</option>
                        <option value="Urea">Urea</option>


                    </select>
                    <span asp-validation-for="Analysis"></span>

                </div>

                <button class="btn btn-slide-9" type="submit" style="background-color:black; margin-left: 50%; color: white; ">Save</button>
            </form>

        </div>
    </section>

    <hr />
    <!-- ************************************************************************************************************* -->
    <a class="btn btn-slide-9" asp-controller="Work" asp-action="patient" type="submit" style="background-color:black; margin-left: 85%; margin-top: 10%; color: white; ">Back &nbsp; <i style="color:white; margin:auto;" class="bi bi-arrow-bar-right"></i> </a>

@section Scripts
    {
    <partial name="_ValidationScriptsPartial.cshtml" />
}

Hospital-Management-System-By-Ibrahim/HMSproject/Views/Search/shictory.cshtml
@using HMSproject.Models;
@model List<Diagnose>

@{
    ViewData["Title"] = "Medical History";
    Layout = "_LayoutDoctor";
}


<style>
    .bg-1 {
        background-image: url("../Doctor/Images/22.jpg");
        background-size: cover;
        position: relative;
    }
</style>
<section class="page-title bg-1">
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="block text-center">
                    <span class="text-white"></span>
                    <h1 class="text-capitalize mb-5 text-lg">Medical History</h1>
                </div>
            </div>
        </div>
    </div>
</section>

<!-- ****************************************Medical History****************************************************** -->
<section class="tab">
    <div class="container">
        <div class="doctor-img-block">
            <h2 style="color:black; font-style: normal;">Patient Medical History</h2>
            <div class="table-wrapper">
                <partial name="_Notification" />
                <table class="fl-table">
                    <thead>
                        <tr>

                            <th> Description</th>
                            <th> prescription</th>
                            <th> Medical Analysis</th>
                            <th> Date</th>
                            <th> Modify</th>

                        </tr>
                    </thead>
                    <tbody>

                        @foreach (var diagnose in Model)
                        {
                            <tr>

                                <td>@diagnose.Description</td>
                                <td>@diagnose.Prescription</td>
                                <td>@diagnose.Analysis</td>
                                <td>@diagnose.Date </td>
                                <td>
                                    <a asp-controller="Search" asp-action="edit" asp-route-Id="@diagnose.Id"><i class="bi bi-pencil-square"></i></a>
                                    &nbsp;

                                    <a asp-controller="Search" asp-action="delete" asp-route-Id="@diagnose.Id"><i class="bi bi-trash3-fill"></i></a>


                                </td>


                            </tr>

                        }


                    <tbody>
                </table>
            </div>
            <hr />
            <hr />
            <a class="btn btn-slide-9" asp-controller="Search" asp-action="spatient" type="submit" style="background-color:black; margin-left: 85%; color: white; argin-top: 10%; ">Back &nbsp; <i style="color:white; margin:auto;" class="bi bi-arrow-bar-right"></i> </a>


        </div>
    </div>
</section>

Hospital-Management-System-By-Ibrahim/HMSproject/Views/Search/spatient.cshtml
@using HMSproject.Models;
@model List<Patient>




@{
    ViewData["Title"] = "Patient";
    Layout = "_LayoutDoctor";
}
    <style>

       
        .bg-1 {
            background-image: url("../Doctor/Images/22.jpg");
            background-size: cover;
            position: relative;
        }
   
        select {

            /* Reset Select */
            appearance: none;
            outline: 0;
            border: 0;
            box-shadow: none;
            /* Personalize */
            flex: 1;
            padding: 0 1em;
            color: #fff;
            background-color: var(--darkgray);
            background-image: none;
            cursor: pointer;
        }
            /* Remove IE arrow */
            select::-ms-expand {
                display: none;
            }
        /* Custom Select wrapper */
        .select {
            position: relative;
            display: flex;
            width: 20em;
            height: 3em;
            border-radius: .25em;
            overflow: hidden;
        }
            /* Arrow */
            .select::after {
                content: '\25BC';
                position: absolute;
                top: 0;
                right: 0;
                padding: 1em;
                background-color: black;
                transition: .25s all ease;
                pointer-events: none;
            }
            /* Transition */
            .select:hover::after {
                color: white;
            }

        /* Other styles*/
        body {
            color: #fff;
        }

        h1 {
            margin: 0 0 0.25em;
        }

        a {
            font-weight: bold;
            color: var(--gray);
            text-decoration: none;
            padding: .25em;
            border-radius: .25em;
            background: white;
        }

    </style>
    <!-- ********************************************************************************************************** -->

    <section class="page-title bg-1">
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="block text-center">
                        <span class="text-white"></span>
                        <h1 class="text-capitalize mb-5 text-lg">Patient Profile</h1>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- *********************************************************************************** -->
<section class="tab">
    <div class="container">


        <div class="doctor-img-block">
            <h2 style="color: black; font-style: normal;">Patient Data</h2>
            <div class="table-wrapper">
                <table class="fl-table">
                    <thead>
                    <tr>
                        <th>Patient Name</th>
                        <th> Age</th>
                        <th> Gander</th>
                        <th>Phone</th>

                        <th> Medical Hictory</th>

                    </tr>
                    </thead>
                    <tbody>
                    @foreach (var Patient in Model)
                    {
                        <tr>
                            <td>@Patient.Name</td>
                            <td>@Patient.Age</td>
                            <td>@Patient.Gender</td>
                            <td>@Patient.PhoneNumber</td>

                            <td>
                                <a class="btn btn-slide-9" asp-action="Shictory" asp-controller="Search" asp-route-Id="@Patient.Id">
                                    <u style="color:darkblue;">Show</u>

                                </a>
                            </td>
                        </tr>
                    }
                    <tbody>
                </table>
            </div>
        </div>
    </div>
</section>
<hr>
<a class="btn btn-slide-9" asp-controller="Work" asp-action="work" type="submit" style="background-color:black; margin-left: 85%; color: white; margin-top: 10%; ">Back &nbsp; <i style="color:white; margin:auto;" class="bi bi-arrow-bar-right"></i> </a>