Hospital-Management-System-By-Ibrahim/HMSproject/Models/Nurse.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using HMSproject.Models;
using Microsoft.EntityFrameworkCore;

namespace HMSproject.Models;

[Table("nurses")]
public partial class Nurse
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("name")]
    [StringLength(30, MinimumLength = 3, ErrorMessage = "Your name must be between 3 and 30 characters")]
    [Unicode(false)]
    public string Name { get; set; } = null!;

    [Column("gender")]
    [StringLength(20)]
    [Unicode(false)]
    public string Gender { get; set; } = null!;

    [Required]
    [Column("fk_dept")]
    [DisplayName("Specialization")]
    public int? FkDept { get; set; }

    [Column("age")]
    [Range(15, 50, ErrorMessage = "Invalid Age, Try Again")]
    public int Age { get; set; }

    [Column("email")]
    [StringLength(255)]
    [DataType(DataType.EmailAddress)]
    [Unicode(false)]
    public string Email { get; set; } = null!;

    [Column("password")]
    [DataType(DataType.Password)]
    [StringLength(100, MinimumLength = 6, ErrorMessage = "Password Length must be at least 6 with special characters like $%#_+,")]
    [Unicode(false)]
    public string Password { get; set; } = null!;

    [Column("phone")]
    [DataType(DataType.PhoneNumber)]
    [StringLength(11, MinimumLength = 11, ErrorMessage = "Phone Number must be 11 characters")]
    [Unicode(false)]
    public string? Phone { get; set; }

    [Column("address")]
    [StringLength(200, MinimumLength = 10, ErrorMessage = "Address must be between 10 and 200 characters")]
    [Unicode(false)]
    public string? Address { get; set; }

    [Column("image")]
    [StringLength(100)]
    [Unicode(false)]
    public string? Image { get; set; }

    [ForeignKey("FkDept")]
    [InverseProperty("Nurses")]
    public virtual Department? FkDeptNavigation { get; set; }
}

Hospital-Management-System-By-Ibrahim/HMSproject/Controllers/NurseController.cs
using HMSproject.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace HMSproject.Controllers
{
    public class NurseController : Controller
    {
        // Make a refrence from HmsContext
        private readonly HmsContext _db;

        //Make a constructor to connect with HmsContext
        public NurseController(HmsContext db)
        {
            _db = db; // have Full Access To DB 
        }

        public IActionResult Index()
        {
            IEnumerable<Nurse> nurseData = _db.Nurses.Include(dept => dept.FkDeptNavigation).ToList();
            return View(nurseData);
        }


        // -- Create --
        // GET
        [HttpGet]
        public IActionResult Create()
        {
            var depts = _db.Departments.FromSql($"SELECT * FROM departments").ToList();
            Dictionary<int, string> data = new Dictionary<int, string>();
            foreach (var dept in depts)
            {
                data.Add(dept.Id, dept.Name);
            }
            ViewBag.Depts = data;
            return View();
        }
        // POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Nurse obj, IFormFile nsImage)
        {
            // Check Image
            if (nsImage == null)
                ModelState.AddModelError("Image", "Please, Select an Image!");

            // Hashing The Password
            var passwordHasher = new PasswordHasher<string>();
            string password = obj.Password;
            string hashedPassword = passwordHasher.HashPassword(null, password);
            // Check Password
            var pass = _db.Nurses.FromSql($"SELECT * FROM nurses WHERE password = {hashedPassword}");
            foreach (var p in pass)
            {
                if (p.Password == null)
                    break;
                else
                {
                    ModelState.AddModelError("Password", "This Password is already exist!!");
                    break;
                }
            }
            // Check Email
            var em = _db.Nurses.FromSql($"SELECT * FROM nurses WHERE email = {obj.Email}");
            foreach (var p in em)
            {
                if (p.Email == null)
                    break;
                else
                {
                    ModelState.AddModelError("Email", "This Email is already exist!!");
                    break;
                }
            }
            // Check Phone
            var ph = _db.Nurses.FromSql($"SELECT * FROM nurses WHERE phone = {obj.Phone}");
            foreach (var p in ph)
            {
                if (p.Phone == null)
                    break;
                else
                {
                    ModelState.AddModelError("Phone", "This Phone is already exist!!");
                    break;
                }
            }

            if (ModelState.IsValid)
            {
                _db.Nurses.Add(obj);
                _db.SaveChanges();

                // Update DataBase
                _db.Database.ExecuteSqlInterpolated($"UPDATE nurses SET password = {hashedPassword} WHERE id = {obj.Id}");
                _db.SaveChanges();

                // Upload The Image
                try
                {
                    // Upload The Image To wwwroot Folder
                    string imageName = nsImage.FileName;
                    imageName = $"{obj.Id}-" + Path.GetFileName(imageName);
                    string uploadFilePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/images/ns", imageName);
                    var stream = new FileStream(uploadFilePath, FileMode.Create);
                    nsImage.CopyToAsync(stream);
                    // Using SQL Queries To Update The Image 
                    using (var trans = _db.Database.BeginTransaction())
                    {
                        _db.Database.ExecuteSqlInterpolated($"UPDATE nurses SET image = {imageName} WHERE id = {obj.Id}");
                        _db.SaveChanges();
                        trans.Commit();
                    }
                }
                catch (Exception e)
                {

                }
                TempData["success"] = "Nurse Created Successfully";
                return RedirectToAction("Index");
            }

            // If there are unknown errors 
            var depts = _db.Departments.FromSql($"SELECT * FROM departments").ToList();
            Dictionary<int, string> data = new Dictionary<int, string>();
            foreach (var dept in depts)
            {
                data.Add(dept.Id, dept.Name);
            }
            ViewBag.Depts = data;

			TempData["error"] = "Oops, Errors Occured!";
			return View(obj);
        }

        // -- Update --
        // GET
        [HttpGet]
        public IActionResult Edit(int? id)
        {
            if (id == 0 || id == null)
                return NotFound();

            var obj = _db.Nurses.Find(id);
            if (obj == null)
                return NotFound();

            var depts = _db.Departments.FromSql($"SELECT * FROM departments").ToList();
            Dictionary<int, string> data = new Dictionary<int, string>();
            foreach (var dept in depts)
            {
                data.Add(dept.Id, dept.Name);
            }
            ViewBag.Depts = data;

            return View(obj);
        }
        // POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Nurse obj)
        {
            // Check Email
            var em = _db.Nurses.FromSql($"SELECT * FROM nurses WHERE email = {obj.Email} AND id != {obj.Id}");
            foreach (var p in em)
            {
                if (p.Email == null)
                    break;
                else
                {
                    ModelState.AddModelError("Email", "This Email is already exist!!");
                    break;
                }
            }
            // Check Phone
            var ph = _db.Nurses.FromSql($"SELECT * FROM nurses WHERE phone = {obj.Phone} AND id != {obj.Id}");
            foreach (var p in ph)
            {
                if (p.Phone == null)
                    break;
                else
                {
                    ModelState.AddModelError("Phone", "This Phone is already exist!!");
                    break;
                }
            }

            if (ModelState.IsValid)
            {
                _db.Nurses.Update(obj);
                _db.SaveChanges();

                TempData["success"] = "Nurse Updated Successfully";
                return RedirectToAction("Index");
            }

            // If there are unknown errors 
            var depts = _db.Departments.FromSql($"SELECT * FROM departments").ToList();
            Dictionary<int, string> data = new Dictionary<int, string>();
            foreach (var dept in depts)
            {
                data.Add(dept.Id, dept.Name);
            }
            ViewBag.Depts = data;

			TempData["error"] = "Oops, Errors Occured!";
			return View(obj);
        }

        // -- Update Password --
        // GET
        [HttpGet]
        public IActionResult EditPass(int? id)
        {
            if (id == 0 || id == null)
                return NotFound();

            var obj = _db.Nurses.Find(id);
            if (obj == null)
                return NotFound();

            var depts = _db.Departments.FromSql($"SELECT * FROM departments").ToList();
            Dictionary<int, string> data = new Dictionary<int, string>();
            foreach (var dept in depts)
            {
                data.Add(dept.Id, dept.Name);
            }
            ViewBag.Depts = data;

            return View(obj);
        }
        // POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult EditPass(Nurse obj)
        {
            // Hashing The Password
            var passwordHasher = new PasswordHasher<string>();
            string password = obj.Password;
            string hashedPassword = passwordHasher.HashPassword(null, password);

            // Check Password
            var pass = _db.Nurses.FromSql($"SELECT * FROM nurses WHERE password = {hashedPassword} AND id != {obj.Id}");
            foreach (var p in pass)
            {
                if (p.Password == null)
                    break;
                else
                {
                    ModelState.AddModelError("Password", "This Password is already exist!!");
                    break;
                }
            }

            if (ModelState.IsValid)
            {
                _db.Nurses.Update(obj);
                _db.SaveChanges();

                // Update Hashing Password
                _db.Database.ExecuteSqlInterpolated($"UPDATE nurses SET password = {hashedPassword} WHERE id = {obj.Id}");
                _db.SaveChanges();

                TempData["success"] = "Password Updated Successfully";
                return RedirectToAction("Index");
            }

            var depts = _db.Departments.FromSql($"SELECT * FROM departments").ToList();
            Dictionary<int, string> data = new Dictionary<int, string>();
            foreach (var dept in depts)
            {
                data.Add(dept.Id, dept.Name);
            }
            ViewBag.Depts = data;

			TempData["error"] = "Oops, Errors Occured!";
			return View(obj);
        }

        // -- Update Image --
        // GET
        public IActionResult EditImage(int? id)
        {
            if (id == 0 || id == null)
                return NotFound();

            var obj = _db.Nurses.Find(id);
            if (obj == null)
                return NotFound();

            var depts = _db.Departments.FromSql($"SELECT * FROM departments").ToList();
            Dictionary<int, string> data = new Dictionary<int, string>();
            foreach (var dept in depts)
            {

Hospital-Management-System-By-Ibrahim/HMSproject/Views/Nurse/Create.cshtml
@{
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}


@using HMSproject.Models;


@model Nurse


<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <strong style="font-size: 25px">Add</strong>
                <span style="color: #3ad896; font-size: 20px">Nurse</span>
                <hr width="" style="margin-top: 0" />
            </div>
            <div class="card-body card-block">
                <form asp-action="Create"
                      method="POST"
                      enctype="multipart/form-data"
                      class="form-horizontal">
                    <div class="row form-group">
                        <div class="col col-md-3">
                            <label for="name" class="form-control-label text-black">Nurse Name</label>
                        </div>
                        <div class="col-12 col-md-9">
                            <input type="text"
                                   id="name"
                                   asp-for="Name"
                                   placeholder="nurse name"
                                   class="form-control" />
                            <span asp-validation-for="Name" class="text-danger font-12"></span>
                        </div>
                    </div>
                    <div class="row form-group mt-4">
                        <div class="col col-md-3">
                            <label for="age" class="form-control-label text-black">Age</label>
                        </div>
                        <div class="col-12 col-md-9">
                            <input type="number"
                                   id="age"
                                   asp-for="Age"
                                   placeholder="nurse age"
                                   class="form-control" />
                            <span asp-validation-for="Age" class="text-danger font-12"></span>
                        </div>
                    </div>
                    <div class="row form-group mt-4">
                        <div class="col col-md-3">
                            <label for="email" class="form-control-label text-black">Email</label>
                        </div>
                        <div class="col-12 col-md-9">
                            <input type="email"
                                   id="email"
                                   asp-for="Email"
                                   placeholder="nurse email"
                                   class="form-control" />
                            <span asp-validation-for="Email" class="text-danger font-12"></span>
                        </div>
                    </div>
                    <div class="row form-group mt-4">
                        <div class="col col-md-3">
                            <label for="ph" class="form-control-label text-black">Phone</label>
                        </div>
                        <div class="col-12 col-md-9">
                            <input type="text"
                                   id="ph"
                                   asp-for="Phone"
                                   placeholder="nurse phone"
                                   class="form-control" />
                            <span asp-validation-for="Phone" class="text-danger font-12"></span>
                        </div>
                    </div>
                    <div class="row form-group mt-4">
                        <div class="col col-md-3">
                            <label for="password" class="form-control-label text-black">Password</label>
                        </div>
                        <div class="col-12 col-md-9">
                            <input type="password"
                                   id="password"
                                   asp-for="Password"
                                   placeholder="nurse password"
                                   class="form-control" />
                            <span asp-validation-for="Password" class="text-danger font-12"></span>
                        </div>
                    </div>
                    <div class="row form-group mt-4">
                        <div class="col col-md-3">
                            <label for="textarea-input"
                                   class="form-control-label text-black">Address</label>
                        </div>
                        <div class="col-12 col-md-9">
                            <textarea asp-for="Address"
                                      id="textarea-input"
                                      rows="5"
                                      placeholder="address..."
                                      class="form-control"></textarea>
                            <span asp-validation-for="Address" class="text-danger font-12"></span>
                        </div>
                    </div>
                    <div class="row form-group mt-4">
                        <div class="col col-md-3">
                            <label for="sp" class="form-control-label text-black">Specialization</label>
                        </div>
                        <div class="col-12 col-md-9">
                            <select class="form-control" asp-for="FkDept">
                                <option value="" disabled selected>please select..</option>
                                @foreach (KeyValuePair<int, string> obj in ViewBag.Depts)
                                {
                                    <option value="@obj.Key">@obj.Value</option>
                                }
                            </select>
                            <span asp-validation-for="FkDept" class="text-danger font-12"></span>
                        </div>
                    </div>
                    <div class="row form-group mt-4">
                        <div class="col col-md-3">
                            <label for="gender" class="form-control-label text-black">Gender</label>
                        </div>
                        <div class="col-12 col-md-9">
                            <select id="gender" class="form-control" asp-for="Gender">
                                <option value="" disabled selected>please select..</option>
                                <option value="male">Male</option>
                                <option value="female">Female</option>
                            </select>
                            <span asp-validation-for="Gender" class="text-danger font-12"></span>
                        </div>
                    </div>
                    <div class="row form-group mt-4">
                        <div class="col col-md-3">
                            <label for="file-input"
                                   class="form-control-label text-black">Nurse Image</label>
                        </div>
                        <div class="col-12 col-md-9">
                            <input type="file"
                                   id="file-input"
                                   asp-for="Image"
                                   name="nsImage"
                                   class="form-control" />
                            <span asp-validation-for="Image" class="text-danger font-12"></span>
                        </div>
                    </div>
                    <div class="card-footer"
                         style="
                    display: flex;
                    justify-content: space-between;
                    margin-top: 25px;
                    background-color: white;
                  ">
                        <button type="submit"
                                class="btn btn-outline-primary btn-sm mx-4">
                            <i class="fas fa-paper-plane"></i> Submit
                        </button>
                        <button type="reset" class="btn btn-outline-danger btn-sm">
                            <i class="fas fa-ban"></i> Reset
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@* Client Side Validation*@
@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

Hospital-Management-System-By-Ibrahim/HMSproject/Views/Nurse/Index.cshtml
@{
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}


@using HMSproject.Models

@model IEnumerable<Nurse>

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title text-dark mb-4 mt-2">Nurses List</h4>
                <div class="table-responsive">
                    <table class="table table-striped">
                        <thead class="bg-dark text-white">
                            <tr>
                                <th class="text-center">Image</th>
                                <th class="text-center">Nurse Name</th>
                                <th class="text-center">Age</th>
                                <th class="text-center">Phone</th>
                                <th class="text-center">Specialization</th>
                                <th class="text-center">Operations</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var obj in Model)
                            {
                                <tr>
                                    <td class="text-center text-black">
                                        <img src="~/images/ns/@obj.Image" height="40px" width="50px" alt="NurseImage">
                                    </td>
                                    <td class="text-center text-dark">@obj.Name</td>
                                    <td class="text-center">@obj.Age</td>
                                    <td class="text-center">@obj.Phone</td>
                                    <td class="text-center text-dark">@obj.FkDeptNavigation.Name</td>
                                    <td class="text-center">
                                        <div class="w-90 btn-group" role="group">
                                            <a asp-controller="Nurse" asp-action="Edit" asp-route-id="@obj.Id" class="btn btn-outline-primary mx-1">
                                                <i class="fas fa-pencil"></i>
                                            </a>
                                            <a asp-controller="Nurse" asp-action="EditPass" asp-route-id="@obj.Id" class="btn btn-outline-primary mx-1">
                                                <i class="fas fa-key"></i>
                                            </a>
                                            <a asp-controller="Nurse" asp-action="EditImage" asp-route-id="@obj.Id" class="btn btn-outline-primary mx-1">
                                                <i class="fas fa-image"></i>
                                            </a>
                                            <form method="POST" asp-action="Delete" asp-route-id="@obj.Id">
                                                <button type="submit" class="btn btn-outline-danger">
                                                    <i class="fas fa-trash"></i>
                                                </button>
                                            </form>
                                        </div>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>