Hospital-Management-System-By-Ibrahim/HMSproject/Models/Doctor.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using HMSproject.Models;
using Microsoft.EntityFrameworkCore;

namespace HMSproject.Models;

[Table("doctors")]
public partial class Doctor
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("name")]
    [StringLength(30, MinimumLength = 3, ErrorMessage = "Your name must be between 3 and 30 characters")]
    [Unicode(false)]
    public string Name { get; set; } = null!;

    [Column("gender")]
    [StringLength(20)]
    [Unicode(false)]
    public string Gender { get; set; } = null!;

    [Required]
    [DisplayName("Specialization")]
    [Column("fk_dept")]
    public int? FkDept { get; set; }

    [Column("age")]
    [Range(20, 70, ErrorMessage = "Invalid Age, Try Again")]
    public int Age { get; set; }

    [Column("email")]
    [StringLength(255)]
    [DataType(DataType.EmailAddress)]
    [Unicode(false)]
    public string Email { get; set; } = null!;

    [Column("password")]
    [DataType(DataType.Password)]
    [StringLength(100, MinimumLength = 6, ErrorMessage = "Password Length must be at least 6 with special characters like $%#_+,")]
    [Unicode(false)]
    public string Password { get; set; } = null!;

    [Column("experience")]
    [Range(1, 40, ErrorMessage = "Invalid Experience Years, Try Again")]
    public int Experience { get; set; }

    [DisplayName("Personal Profile")]
    [Column("personal_profile")]
    [StringLength(200, MinimumLength = 10, ErrorMessage = "Personal Profile must be between 10 and 200 characters")]
    [Unicode(false)]
    public string PersonalProfile { get; set; } = null!;

    [Column("phone")]
    [DataType(DataType.PhoneNumber)]
    [StringLength(11, MinimumLength = 11, ErrorMessage = "Phone Number must be 11 characters")]
    [Unicode(false)]
    public string? Phone { get; set; }

    [Column("address")]
    [StringLength(200, MinimumLength = 10, ErrorMessage = "Address must be between 10 and 200 characters")]
    [Unicode(false)]
    public string? Address { get; set; }

    [Column("image")]
    [StringLength(100)]
    [Unicode(false)]
    public string? Image { get; set; }

    [ForeignKey("FkDept")]
    [InverseProperty("Doctors")]
    public virtual Department? FkDeptNavigation { get; set; }
}

Hospital-Management-System-By-Ibrahim/HMSproject/Controllers/DoctorController.cs
using HMSproject.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Microsoft.CodeAnalysis.VisualBasic.Syntax;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System.Dynamic;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Identity;

namespace HMSproject.Controllers
{
    public class DoctorController : Controller
    {
        // Make a refrence from HmsContext
        private readonly HmsContext _db;

        //Make a constructor to connect with HmsContext
        public DoctorController(HmsContext db)
        {
            _db = db; // have Full Access To DB 
        }

        public IActionResult Index()
        {
            IEnumerable<Doctor> drData = _db.Doctors.Include(dept => dept.FkDeptNavigation).ToList();
            return View(drData);
        }

        // -- Create --
        // GET
        [HttpGet]
        public IActionResult Create()
        {
            var depts = _db.Departments.FromSql($"SELECT * FROM departments").ToList();
            Dictionary<int, string> data = new Dictionary<int, string>();
            foreach (var dept in depts)
            {
                data.Add(dept.Id, dept.Name);
            }
            ViewBag.Depts = data;
            return View();
        }
        // POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Doctor obj, IFormFile drImage)
        {
            // Check Image
            if(drImage == null)
				ModelState.AddModelError("Image", "Please, Select an Image!");

            // Hashing The Password
            var passwordHasher = new PasswordHasher<string>();
            string password = obj.Password;
            string hashedPassword = passwordHasher.HashPassword(null, password);
            // Check Password
            var pass = _db.Doctors.FromSql($"SELECT * FROM doctors WHERE password = {hashedPassword}");
			foreach (var p in pass)
			{
				if (p.Password == null)
					break;
				else
				{
					ModelState.AddModelError("Password", "This Password is already exist!!");
					break;
				}
			}
			// Check Email
			var em = _db.Doctors.FromSql($"SELECT * FROM doctors WHERE email = {obj.Email}");
			foreach (var p in em)
			{
				if (p.Email == null)
					break;
				else
				{
					ModelState.AddModelError("Email", "This Email is already exist!!");
					break;
				}
			}
			// Check Phone
			var ph = _db.Doctors.FromSql($"SELECT * FROM doctors WHERE phone = {obj.Phone}");
			foreach (var p in ph)
			{
				if (p.Phone == null)
					break;
				else
				{
					ModelState.AddModelError("Phone", "This Phone is already exist!!");
					break;
				}
			}

            if (ModelState.IsValid)
            {
                _db.Doctors.Add(obj);
                _db.SaveChanges();

                // Update DataBase
                _db.Database.ExecuteSqlInterpolated($"UPDATE doctors SET password = {hashedPassword} WHERE id = {obj.Id}");
                _db.SaveChanges();

                // Upload The Image
                try
                {
                    // Upload The Image To wwwroot Folder
                    string imageName = drImage.FileName;
                    imageName = $"{obj.Id}-" + Path.GetFileName(imageName);
                    string uploadFilePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/images/dr", imageName);
                    var stream = new FileStream(uploadFilePath, FileMode.Create);
                    drImage.CopyToAsync(stream);
                    // Using SQL Queries To Update The Image 
                    using (var trans = _db.Database.BeginTransaction())
                    {
                        _db.Database.ExecuteSqlInterpolated($"UPDATE doctors SET image = {imageName} WHERE id = {obj.Id}");
                        _db.SaveChanges();
                        trans.Commit();
                    }
                }
                catch (Exception e)
                {
                    TempData["error"] = "Oops, Errors Occured!";
                    return View(obj);
                }

                TempData["success"] = "Doctor Created Successfully";

                return RedirectToAction("Index");
            }
            // If there are unknown errors 
            var depts = _db.Departments.FromSql($"SELECT * FROM departments").ToList();
            Dictionary<int, string> data = new Dictionary<int, string>();
            foreach (var dept in depts)
            {
                data.Add(dept.Id, dept.Name);
            }
            ViewBag.Depts = data;

			TempData["error"] = "Oops, Errors Occured!";
			return View(obj);
        }

        // -- Update --
        // GET
        public IActionResult Edit(int? id)
        {
            if (id == 0 || id == null)
                return NotFound();

            var obj = _db.Doctors.Find(id);
            if (obj == null)
                return NotFound();

            var depts = _db.Departments.FromSql($"SELECT * FROM departments").ToList();
            Dictionary<int, string> data = new Dictionary<int, string>();
            foreach (var dept in depts)
            {
                data.Add(dept.Id, dept.Name);
            }
            ViewBag.Depts = data;

            return View(obj);
        }
        // POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Doctor obj)
        {
			// Check Email
			var em = _db.Doctors.FromSql($"SELECT * FROM doctors WHERE email = {obj.Email} AND id != {obj.Id}");
			foreach (var p in em)
			{
				if (p.Email == null)
					break;
				else
				{
					ModelState.AddModelError("Email", "This Email is already exist!!");
					break;
				}
			}
			// Check Phone
			var ph = _db.Doctors.FromSql($"SELECT * FROM doctors WHERE phone = {obj.Phone} AND id != {obj.Id}");
			foreach (var p in ph)
			{
				if (p.Phone == null)
					break;
				else
				{
					ModelState.AddModelError("Phone", "This Phone is already exist!!");
					break;
				}
			}

			if (ModelState.IsValid)
            {
                // Update Changed Date
                _db.Doctors.Update(obj);
                _db.SaveChanges();
				TempData["success"] = "Doctor Updated Successfully";
				return RedirectToAction("Index");
            }

			// If there are unknown errors 
			var depts = _db.Departments.FromSql($"SELECT * FROM departments").ToList();
			Dictionary<int, string> data = new Dictionary<int, string>();
			foreach (var dept in depts)
			{
				data.Add(dept.Id, dept.Name);
			}
			ViewBag.Depts = data;

			TempData["error"] = "Oops, Errors Occured!";
			return View(obj);
        }

        // -- Update Password --
        // GET
        public IActionResult EditPass(int? id)
        {
            if (id == 0 || id == null)
                return NotFound();

            var obj = _db.Doctors.Find(id);
            if (obj == null)
                return NotFound();

            var depts = _db.Departments.FromSql($"SELECT * FROM departments").ToList();
            Dictionary<int, string> data = new Dictionary<int, string>();
            foreach (var dept in depts)
            {
                data.Add(dept.Id, dept.Name);
            }
            ViewBag.Depts = data;

            return View(obj);
        }
        // POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult EditPass(Doctor obj)
        {
            // Hashing The Password
            var passwordHasher = new PasswordHasher<string>();
            string password = obj.Password;
            string hashedPassword = passwordHasher.HashPassword(null, password);
            
            // Check Password
            var pass = _db.Doctors.FromSql($"SELECT * FROM doctors WHERE password = {hashedPassword} AND id != {obj.Id}");
			foreach (var p in pass)
			{
				if (p.Password == null)
					break;
				else
				{
					ModelState.AddModelError("Password", "This Password is already exist!!");
					break;
				}
			}

			if (ModelState.IsValid)
            {
                _db.Doctors.Update(obj);
                _db.SaveChanges();

                // Update Hashing Password
                _db.Database.ExecuteSqlInterpolated($"UPDATE doctors SET password = {hashedPassword} WHERE id = {obj.Id}");
                _db.SaveChanges();

                TempData["success"] = "Password Updated Successfully";
                return RedirectToAction("Index");
            }

			// If there are unknown errors 
			var depts = _db.Departments.FromSql($"SELECT * FROM departments").ToList();
			Dictionary<int, string> data = new Dictionary<int, string>();
			foreach (var dept in depts)
			{
				data.Add(dept.Id, dept.Name);
			}
			ViewBag.Depts = data;

			TempData["error"] = "Oops, Errors Occured!";
			return View(obj);
        }

        // -- Update Image --
        // GET
        public IActionResult EditImage(int? id)
        {
            if (id == 0 || id == null)
                return NotFound();

            var obj = _db.Doctors.Find(id);
            if (obj == null)
                return NotFound();

            var depts = _db.Departments.FromSql($"SELECT * FROM departments").ToList();
            Dictionary<int, string> data = new Dictionary<int, string>();
            foreach (var dept in depts)
            {
                data.Add(dept.Id, dept.Name);
            }
            ViewBag.Depts = data;

            return View(obj);
        }
        // POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult EditImage(Doctor obj, IFormFile drImage)
        {
			// Check Image
			if (drImage == null)
				ModelState.AddModelError("Image", "Please, Select an Image!");

			if (ModelState.IsValid)
            {
                _db.Doctors.Update(obj);
                _db.SaveChanges();

                // Update The Image if the user choose to change his image
                try
                {

Hospital-Management-System-By-Ibrahim/HMSproject/Views/Doctor/Doctors.cshtml
@{
    ViewData["Title"] = "Doctors";
    Layout = "_Layout";
}

@model IEnumerable<Doctor>


<section class="page-title bg-1">
  <div class="overlay"></div>
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="block text-center">
          <span class="text-white">All Doctors</span>
          <h1 class="text-capitalize mb-5 text-lg">Specalized doctors</h1>

          <ul class="list-inline breadcumb-nav">
            <li class="list-inline-item">
              <a asp-action="Index" class="text-white">Home</a>
            </li>
            <li class="list-inline-item">
              <span class="text-white">/</span>
            </li>
            <li class="list-inline-item">
              <a href="#" class="text-white-50">All Doctors</a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</section>

<!-- portfolio -->
<section class="section doctors">
    <div class="container">
        <div class="row justify-content-center">
          <div class="col-lg-6 text-center">
            <div class="section-title">
              <h2>Doctors</h2>
              <div class="divider mx-auto my-4"></div>
              <p>
                 Each of our doctors has undergone rigorous training and has years of experience in their field.
                 They are committed to staying up-to-date with the latest medical advancements to ensure that you receive the most effective treatments.
              </p>
            </div>
          </div>
        </div>

        <div class="row shuffle-wrapper portfolio-gallery">
            @foreach(var obj in Model) {
                <div class="col-lg-4 col-sm-6 col-md-6 mb-4 shuffle-item">
                  <div class="position-relative doctor-inner-box">
                    <div class="doctor-profile">
                      <div class="doctor-img">
                        <img
                          src="~/images/dr/@obj.Image"
                          alt="doctor-image"
                          class="img-fluid w-100"
                        />
                      </div>
                    </div>
                    <div class="content mt-3">
                      <h4 class="mb-0">
                        <a asp-controller="Doctor" asp-action="SingleDoctor" asp-route-id="@obj.Id">@obj.Name</a>
                      </h4>
                      <p>@obj.FkDeptNavigation.Name</p>
                    </div>
                  </div>
                </div>
            }
        </div>
    </div>
</section>
<!-- /portfolio -->
<section class="section cta-page">
  <div class="container">
    <div class="row">
      <div class="col-lg-7">
        <div class="cta-content">
          <div class="divider mb-4"></div>
          <h2 class="mb-5 text-lg">
            We are pleased to offer you the
            <span class="title-color">chance to have the healthy</span>
          </h2>
          <a asp-controller="Appointment" asp-action="Create" class="btn btn-main-2 btn-round-full"
          >Get appoinment<i class="icofont-simple-right ml-2"></i
          ></a>
        </div>
      </div>
    </div>
  </div>
</section>

Hospital-Management-System-By-Ibrahim/HMSproject/Views/Doctor/Index.cshtml
@{
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}


@using HMSproject.Models;

@model IEnumerable<Doctor>


<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title text-dark mb-4 mt-2">Doctors List</h4>
                <div class="table-responsive">
                    <table class="table table-striped">
                        <thead class="bg-dark text-white">
                            <tr>
                                <th class="text-center">Image</th>
                                <th class="text-center">Doctor Name</th>
                                @*<th class="text-center">Gender</th>*@
                                <th class="text-center">Experience <small>(years)</small></th>
                                <th class="text-center">Phone</th>
                                <th class="text-center">Specialization</th>
                                <th class="text-center">operations</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach(var obj in Model) {
                                <tr>
                                    <td class="text-center text-black">
                                        <img src="~/images/dr/@obj.Image" height="40px" width="50px" alt="DrImage">
                                    </td>
                                    <td class="text-center text-dark">@obj.Name</td>
                                    @*<td class="text-center">@obj.Gender</td>*@
                                    <td class="text-center">@obj.Experience</td>
                                    <td class="text-center">@obj.Phone</td>
                                    <td class="text-center text-dark">@obj.FkDeptNavigation.Name</td>
                                    
                                    <td class="text-center">
                                        <div class="w-90 btn-group" role="group">
                                            <a asp-controller="Doctor" asp-action="Edit" asp-route-id="@obj.Id" class="btn btn-outline-primary mx-1">
                                                <i class="fas fa-pencil" ></i>
                                            </a>
                                            <a asp-controller="Doctor" asp-action="EditPass" asp-route-id="@obj.Id" class="btn btn-outline-primary mx-1">
                                                <i class="fas fa-key"></i>
                                            </a>
                                            <a asp-controller="Doctor" asp-action="EditImage" asp-route-id="@obj.Id" class="btn btn-outline-primary mx-1">
                                                <i class="fas fa-image"></i>
                                            </a>
                                            <form method="POST" asp-action="Delete" asp-route-id="@obj.Id">
                                                <button type="submit" class="btn btn-outline-danger">
                                                    <i class="fas fa-trash"></i>
                                                </button>
                                            </form>
                                        </div>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

Hospital-Management-System-By-Ibrahim/HMSproject/Views/Doctor/SingleDoctor.cshtml
@model Doctor

@{
    ViewData["Title"] = $"{ViewBag.DrName}";
    Layout = "_Layout";
}

<section class="page-title bg-1">
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="block text-center">
                    <span class="text-white">Doctor Details</span>
                    <h1 class="text-capitalize mb-5 text-lg">@ViewBag.DrName</h1>

                    <ul class="list-inline breadcumb-nav">
                        <li class="list-inline-item">
                            <a asp-controller="Home" asp-action="Index" class="text-white">Home</a>
                        </li>
                        <li class="list-inline-item">
                            <span class="text-white">/</span>
                        </li>
                        <li class="list-inline-item">
                            <a asp-controller="Doctor" asp-action="SingleDoctor" class="text-white-50">Doctor Details</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="section doctor-single">
    <div class="container">
        @foreach(var obj in ViewBag.Doctor) {
            <div class="row">
                <div class="col-lg-4 col-md-6">
                    <div class="doctor-img-block">
                        <img src="~/images/dr/@obj.Image" alt="Doctor-Image" class="img-fluid w-100" />

                        <div class="info-block mt-4">
                            <h4 class="mb-0">@obj.Name</h4>
                            <p>@ViewBag.DeptName</p>

                            <ul class="list-inline mt-4 doctor-social-links">
                                <li class="list-inline-item">
                                    <a href="#!"><i class="icofont-facebook"></i></a>
                                </li>
                                <li class="list-inline-item">
                                    <a href="#!"><i class="icofont-twitter"></i></a>
                                </li>
                                <li class="list-inline-item">
                                    <a href="#!"><i class="icofont-skype"></i></a>
                                </li>
                                <li class="list-inline-item">
                                    <a href="#!"><i class="icofont-linkedin"></i></a>
                                </li>
                                <li class="list-inline-item">
                                    <a href="#!"><i class="icofont-pinterest"></i></a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>

                <div class="col-lg-8 col-md-6">
                    <div class="doctor-details mt-4 mt-lg-0">
                        <h2 class="text-md">Introducing to myself</h2>
                        <div class="divider my-4"></div>
                        <p>
                            @obj.PersonalProfile
                        </p>
                        <p>
                            Dr. @ViewBag.DrName is a board-certified @ViewBag.DeptName who has been practicing medicine for @obj.Experience years. He received his medical degree from Harvard University in 2010. After completing his residency in @ViewBag.DeptName Program at Haravrd University, Dr. @ViewBag.DrName went on to complete a fellowship in @ViewBag.DeptName Program.
                        </p>

                        <a asp-controller="Appointment"
                       asp-action="Create"
                           class="btn btn-main-2 btn-round-full mt-3">
                            Make an Appoinment<i class="icofont-simple-right ml-2"></i>
                        </a>
                    </div>
                </div>
            </div>
        }
    </div>
</section>

<section class="section doctor-qualification gray-bg">
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <div class="section-title">
                    <h3>My Educational Qualifications</h3>
                    <div class="divider my-4"></div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-6 mb-4 mb-lg-0">
                <div class="edu-block mb-5">
                    <span class="h6 text-muted">Year(2005-2007) </span>
                    <h4 class="mb-3 title-color">
                        MBBS, M.D at University of Wyoming
                    </h4>
                    <p>
                        Earn a bachelor's degree. Most medical schools require applicants to have a bachelor's degree, although some schools may accept applicants with a high school diploma and relevant work experience.
                    </p>
                </div>
            </div>
            <div class="col-lg-6">
                <div class="edu-block">
                    <span class="h6 text-muted">Year(2007-2009) </span>
                    <h4 class="mb-3 title-color">
                        M.D. of Netherland Medical College
                    </h4>
                    <p>
                        Earn a bachelor's degree. Most medical schools require applicants to have a bachelor's degree, although some schools may accept applicants with a high school diploma and relevant work experience.
                    </p>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="section doctor-skills">
    <div class="container">
        <div class="row">
            <div class="col-lg-4">
                <h3>My skills</h3>
                <div class="divider my-4"></div>
                <p>
                    Dr. @ViewBag.DrName have a deep understanding of human anatomy, physiology, and pathophysiology. He also be familiar with the latest medical treatments and procedures.
                </p>
            </div>
            <div class="col-lg-4">
                <div class="skill-list">
                    <h5 class="mb-4">Expertise area</h5>
                    <ul class="list-unstyled department-service">
                        <li>
                            <i class="icofont-check mr-2"></i>International Drug Database
                        </li>
                        <li>
                            <i class="icofont-check mr-2"></i>Stretchers and Stretcher
                            Accessories
                        </li>
                        <li>
                            <i class="icofont-check mr-2"></i>Cushions and Mattresses
                        </li>
                        <li>
                            <i class="icofont-check mr-2"></i>Cholesterol and lipid tests
                        </li>
                        <li>
                            <i class="icofont-check mr-2"></i>Critical Care Medicine
                            Specialists
                        </li>
                        <li><i class="icofont-check mr-2"></i>Emergency Assistance</li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="sidebar-widget gray-bg p-4">
                    <h5 class="mb-4">Make Appoinment
                    </h5>

                    <ul class="list-unstyled lh-35">
                        <li class="d-flex justify-content-between align-items-center">
                            Sun - Wed : <span>8:00 - 17:00</span>
                        </li>
                        <li class="d-flex justify-content-between align-items-center">
                            Thu - Fri : <span>9:00 - 17:00</span>
                        </li>
                        <li class="d-flex justify-content-between align-items-center">
                            Sat - sun : <span>10:00 - 17:00</span>
                        </li>
                    </ul>

                    <div class="sidebar-contatct-info mt-4">
                        <p class="mb-0">Need Urgent Help?</p>
                        <h3 class="text-color-2">+23-4565-65768</h3>
                    </div>
                    
                </div>
                <a asp-controller="Appointment"
                   asp-action="Create"
                   class="btn btn-main-2 btn-round-full">
                    Make an Appoinment<i class="icofont-simple-right ml-2"></i>
                </a>
            </div>
        </div>
    </div>
</section>