Hospital-Management-System-By-Ibrahim/HMSproject/Models/Doctor.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using HMSproject.Models;
using Microsoft.EntityFrameworkCore;

namespace HMSproject.Models;

[Table("doctors")]
public partial class Doctor
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("name")]
    [StringLength(30, MinimumLength = 3, ErrorMessage = "Your name must be between 3 and 30 characters")]
    [Unicode(false)]
    public string Name { get; set; } = null!;

    [Column("gender")]
    [StringLength(20)]
    [Unicode(false)]
    public string Gender { get; set; } = null!;

    [Required]
    [DisplayName("Specialization")]
    [Column("fk_dept")]
    public int? FkDept { get; set; }

    [Column("age")]
    [Range(20, 70, ErrorMessage = "Invalid Age, Try Again")]
    public int Age { get; set; }

    [Column("email")]
    [StringLength(255)]
    [DataType(DataType.EmailAddress)]
    [Unicode(false)]
    public string Email { get; set; } = null!;

    [Column("password")]
    [DataType(DataType.Password)]
    [StringLength(100, MinimumLength = 6, ErrorMessage = "Password Length must be at least 6 with special characters like $%#_+,")]
    [Unicode(false)]
    public string Password { get; set; } = null!;

    [Column("experience")]
    [Range(1, 40, ErrorMessage = "Invalid Experience Years, Try Again")]
    public int Experience { get; set; }

    [DisplayName("Personal Profile")]
    [Column("personal_profile")]
    [StringLength(200, MinimumLength = 10, ErrorMessage = "Personal Profile must be between 10 and 200 characters")]
    [Unicode(false)]
    public string PersonalProfile { get; set; } = null!;

    [Column("phone")]
    [DataType(DataType.PhoneNumber)]
    [StringLength(11, MinimumLength = 11, ErrorMessage = "Phone Number must be 11 characters")]
    [Unicode(false)]
    public string? Phone { get; set; }

    [Column("address")]
    [StringLength(200, MinimumLength = 10, ErrorMessage = "Address must be between 10 and 200 characters")]
    [Unicode(false)]
    public string? Address { get; set; }

    [Column("image")]
    [StringLength(100)]
    [Unicode(false)]
    public string? Image { get; set; }

    [ForeignKey("FkDept")]
    [InverseProperty("Doctors")]
    public virtual Department? FkDeptNavigation { get; set; }
}

Hospital-Management-System-By-Ibrahim/HMSproject/Controllers/DoctorController.cs
using HMSproject.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Microsoft.CodeAnalysis.VisualBasic.Syntax;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System.Dynamic;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Identity;

namespace HMSproject.Controllers
{
    public class DoctorController : Controller
    {
        // Make a refrence from HmsContext
        private readonly HmsContext _db;

        //Make a constructor to connect with HmsContext
        public DoctorController(HmsContext db)
        {
            _db = db; // have Full Access To DB 
        }

        public IActionResult Index()
        {
            IEnumerable<Doctor> drData = _db.Doctors.Include(dept => dept.FkDeptNavigation).ToList();
            return View(drData);
        }

        // -- Create --
        // GET
        [HttpGet]
        public IActionResult Create()
        {
            var depts = _db.Departments.FromSql($"SELECT * FROM departments").ToList();
            Dictionary<int, string> data = new Dictionary<int, string>();
            foreach (var dept in depts)
            {
                data.Add(dept.Id, dept.Name);
            }
            ViewBag.Depts = data;
            return View();
        }
        // POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Doctor obj, IFormFile drImage)
        {
            // Check Image
            if(drImage == null)
				ModelState.AddModelError("Image", "Please, Select an Image!");

            // Hashing The Password
            var passwordHasher = new PasswordHasher<string>();
            string password = obj.Password;
            string hashedPassword = passwordHasher.HashPassword(null, password);
            // Check Password
            var pass = _db.Doctors.FromSql($"SELECT * FROM doctors WHERE password = {hashedPassword}");
			foreach (var p in pass)
			{
				if (p.Password == null)
					break;
				else
				{
					ModelState.AddModelError("Password", "This Password is already exist!!");
					break;
				}
			}
			// Check Email
			var em = _db.Doctors.FromSql($"SELECT * FROM doctors WHERE email = {obj.Email}");
			foreach (var p in em)
			{
				if (p.Email == null)
					break;
				else
				{
					ModelState.AddModelError("Email", "This Email is already exist!!");
					break;
				}
			}
			// Check Phone
			var ph = _db.Doctors.FromSql($"SELECT * FROM doctors WHERE phone = {obj.Phone}");
			foreach (var p in ph)
			{
				if (p.Phone == null)
					break;
				else
				{
					ModelState.AddModelError("Phone", "This Phone is already exist!!");
					break;
				}
			}

            if (ModelState.IsValid)
            {
                _db.Doctors.Add(obj);
                _db.SaveChanges();

                // Update DataBase
                _db.Database.ExecuteSqlInterpolated($"UPDATE doctors SET password = {hashedPassword} WHERE id = {obj.Id}");
                _db.SaveChanges();

                // Upload The Image
                try
                {
                    // Upload The Image To wwwroot Folder
                    string imageName = drImage.FileName;
                    imageName = $"{obj.Id}-" + Path.GetFileName(imageName);
                    string uploadFilePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/images/dr", imageName);
                    var stream = new FileStream(uploadFilePath, FileMode.Create);
                    drImage.CopyToAsync(stream);
                    // Using SQL Queries To Update The Image 
                    using (var trans = _db.Database.BeginTransaction())
                    {
                        _db.Database.ExecuteSqlInterpolated($"UPDATE doctors SET image = {imageName} WHERE id = {obj.Id}");
                        _db.SaveChanges();
                        trans.Commit();
                    }
                }
                catch (Exception e)
                {
                    TempData["error"] = "Oops, Errors Occured!";
                    return View(obj);
                }

                TempData["success"] = "Doctor Created Successfully";

                return RedirectToAction("Index");
            }
            // If there are unknown errors 
            var depts = _db.Departments.FromSql($"SELECT * FROM departments").ToList();
            Dictionary<int, string> data = new Dictionary<int, string>();
            foreach (var dept in depts)
            {
                data.Add(dept.Id, dept.Name);
            }
            ViewBag.Depts = data;

			TempData["error"] = "Oops, Errors Occured!";
			return View(obj);
        }

        // -- Update --
        // GET
        public IActionResult Edit(int? id)
        {
            if (id == 0 || id == null)
                return NotFound();

            var obj = _db.Doctors.Find(id);
            if (obj == null)
                return NotFound();

            var depts = _db.Departments.FromSql($"SELECT * FROM departments").ToList();
            Dictionary<int, string> data = new Dictionary<int, string>();
            foreach (var dept in depts)
            {
                data.Add(dept.Id, dept.Name);
            }
            ViewBag.Depts = data;

            return View(obj);
        }
        // POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Doctor obj)
        {
			// Check Email
			var em = _db.Doctors.FromSql($"SELECT * FROM doctors WHERE email = {obj.Email} AND id != {obj.Id}");
			foreach (var p in em)
			{
				if (p.Email == null)
					break;
				else
				{
					ModelState.AddModelError("Email", "This Email is already exist!!");
					break;
				}
			}
			// Check Phone
			var ph = _db.Doctors.FromSql($"SELECT * FROM doctors WHERE phone = {obj.Phone} AND id != {obj.Id}");
			foreach (var p in ph)
			{
				if (p.Phone == null)
					break;
				else
				{
					ModelState.AddModelError("Phone", "This Phone is already exist!!");
					break;
				}
			}

			if (ModelState.IsValid)
            {
                // Update Changed Date
                _db.Doctors.Update(obj);
                _db.SaveChanges();
				TempData["success"] = "Doctor Updated Successfully";
				return RedirectToAction("Index");
            }

			// If there are unknown errors 
			var depts = _db.Departments.FromSql($"SELECT * FROM departments").ToList();
			Dictionary<int, string> data = new Dictionary<int, string>();
			foreach (var dept in depts)
			{
				data.Add(dept.Id, dept.Name);
			}
			ViewBag.Depts = data;

			TempData["error"] = "Oops, Errors Occured!";
			return View(obj);
        }

        // -- Update Password --
        // GET
        public IActionResult EditPass(int? id)
        {
            if (id == 0 || id == null)
                return NotFound();

            var obj = _db.Doctors.Find(id);
            if (obj == null)
                return NotFound();

            var depts = _db.Departments.FromSql($"SELECT * FROM departments").ToList();
            Dictionary<int, string> data = new Dictionary<int, string>();
            foreach (var dept in depts)
            {
                data.Add(dept.Id, dept.Name);
            }
            ViewBag.Depts = data;

            return View(obj);
        }
        // POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult EditPass(Doctor obj)
        {
            // Hashing The Password
            var passwordHasher = new PasswordHasher<string>();
            string password = obj.Password;
            string hashedPassword = passwordHasher.HashPassword(null, password);
            
            // Check Password
            var pass = _db.Doctors.FromSql($"SELECT * FROM doctors WHERE password = {hashedPassword} AND id != {obj.Id}");
			foreach (var p in pass)
			{
				if (p.Password == null)
					break;
				else
				{
					ModelState.AddModelError("Password", "This Password is already exist!!");
					break;
				}
			}

			if (ModelState.IsValid)
            {
                _db.Doctors.Update(obj);
                _db.SaveChanges();

                // Update Hashing Password
                _db.Database.ExecuteSqlInterpolated($"UPDATE doctors SET password = {hashedPassword} WHERE id = {obj.Id}");
                _db.SaveChanges();

                TempData["success"] = "Password Updated Successfully";
                return RedirectToAction("Index");
            }

			// If there are unknown errors 
			var depts = _db.Departments.FromSql($"SELECT * FROM departments").ToList();
			Dictionary<int, string> data = new Dictionary<int, string>();
			foreach (var dept in depts)
			{
				data.Add(dept.Id, dept.Name);
			}
			ViewBag.Depts = data;

			TempData["error"] = "Oops, Errors Occured!";
			return View(obj);
        }

        // -- Update Image --
        // GET
        public IActionResult EditImage(int? id)
        {
            if (id == 0 || id == null)
                return NotFound();

            var obj = _db.Doctors.Find(id);
            if (obj == null)
                return NotFound();

            var depts = _db.Departments.FromSql($"SELECT * FROM departments").ToList();
            Dictionary<int, string> data = new Dictionary<int, string>();
            foreach (var dept in depts)
            {
                data.Add(dept.Id, dept.Name);
            }
            ViewBag.Depts = data;

            return View(obj);
        }
        // POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult EditImage(Doctor obj, IFormFile drImage)
        {
			// Check Image
			if (drImage == null)
				ModelState.AddModelError("Image", "Please, Select an Image!");

			if (ModelState.IsValid)
            {
                _db.Doctors.Update(obj);
                _db.SaveChanges();

                // Update The Image if the user choose to change his image
                try
                {

Hospital-Management-System-By-Ibrahim/HMSproject/Controllers/HomeDoctorController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using HMSproject.Models;

namespace HMSproject.Controllers
{
    public class HomeDoctorController : Controller
    {
	    public HomeDoctorController(HmsContext db)
	    {
		    _db = db;
	    }

	    private readonly HmsContext _db;

		/*------------------------------------------------------------------------------*/



		public IActionResult Index()
        {
            return View();
        }

		/*------------------------------------------------------------------------------*/
		public IActionResult Doctor()
		{
			return View();
		}

		public IActionResult Close()
		{
			var patients = _db.AspNetUsers.ToList();
			foreach(var patient in patients) 
			{
				patient.Condition = 0;
				_db.Update(patient);
			}

			_db.SaveChanges();

			return RedirectToAction("Index","Home");
		}


		

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel{ RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }

	
}

Hospital-Management-System-By-Ibrahim/HMSproject/Controllers/ProfileController.cs
using Microsoft.AspNetCore.Mvc;

namespace HMSproject.Controllers
{
    public class ProfileController : Controller
    {
        public IActionResult Profile()
        {
            return View();
        }
    }
}

Hospital-Management-System-By-Ibrahim/HMSproject/Views/HomeDoctor/Index.cshtml
@{
	ViewData["Title"] = "Dashboard";
	Layout = "_LayoutDoctor";
}
	<style>
    .bg-1 {
        /*background-image: url("/Doctor/Images/22.jpg");*/
        background-size: cover;
        position: relative;
    }


    /*-------------------------------------------------*/

	body {
		margin: 0;
		padding: 0;
		background: #fafafa;
		color: #fff;
	}

	.maain {
		position: relative;
		height: 100vh;
		width: 100%;
		top: 0;
		left: 0;

		right: 0;
	}

		.maain .overrlay {
			position: absolute;
			top: 0;
			left: 0;
			width: 100%;
			height: 100%;

		
			z-index: 0;
		}

		.maain #video {
			position: absolute;
			z-index: -1;
			min-height: 100%;
			min-width: 100%;
			width: 100%;
			height: 100%;
			left: 0;
			right: 0;
			top: 0;
			bottom: 0;

			object-fit: cover;
		}

		.maain .naavbar {
			position: absolute;
			height: auto;
			width: 100%;
			margin: 2% 0;
			display: flex;
			align-items: center;
			overflow: hidden;
			padding: 10px 0;
		}

			.maain .naavbar .logo {
				position: relative;
				height: auto;
				width: 10%;
				left: 10%;
				top:2%;
				float: left;
				font-family: 'Lato',sans-serif;
				font-size: 35px;
				font-weight: 600;
				cursor: pointer;
				text-shadow: 0px 0.5px 5px rgba(0, 0, 0, 0.2);
				transition: 0.1s ease-in-out;
			}

				.maain .naavbar .logo:hover {
					color: rgba(0, 0, 0, 0.4);
				}

		.maain .heading {
			position: absolute;
			height: auto;
			width: 100%;
			top: 50%;
			transform: translateY(-50%);
			text-align: left;
			text-shadow: 0px 0.5px 5px rgba(0, 0, 0, 0.2);
		}

			.maain .heading .head {
				position: relative;
				font-family: 'RacingSansOne',sans-serif;
				font-size: 48px;
				font-weight: 600;
				color: #fff;
				left:8%;
			}

				.maain .heading .head span {
					color:black;
				}

				.maain .heading .sub span {
					color: black;
				}


			.maain .heading .sub {
				position: relative;
				font-family: 'cinzel',sans-serif;
				font-size: 22px;
				font-weight: 300;
				color: #fff;
				left: 15%;
				margin: -2% 0 2% 0;
			}

			.maain .heading .bttns {
				height: auto;
				width: 100%;
				display: flex;
				text-align: center;
				align-items: center;
				justify-content: left;
				position: relative;
				left:15%;
			}

				.maain .heading .bttns a {
					color: #fff;
					text-align: center;
					text-decoration: none;
					font-family: 'cinzel',sans-serif;
					font-size: 15px;
					font-weight: 300;
					display: block;
					border: 1px solid rgba(255, 255, 255, 0.5);
					height: auto;
					width: 150px;
					padding: 10px;
					display: flex;
				
					align-items: center;
					justify-content: center;
					margin-left: 1%;
					border-radius: 2px;
					transition: 0.5s ease-in-out;
				}

					.maain .heading .bttns a:hover {
						background: black;
						border: 1px solid #017fb5;
					}

				.maain .heading .bttns .btn1 {
					background: black;
					border: 1px solid #017fb5;
					left :50%;
				}

					.maain .heading .bttns .btn1:hover {
						background: #017fb5;
						border: 1px solid #017fb5;
						color: rgba(255, 255, 255, 0.95);
					}
					</style>
	


@*<a class="btn btn-slide-9" asp-controller="Home" asp-action="doctor" style="background-color:mediumvioletred; margin-left: 46%; color: white;">Work Start</a>
*@
<!-- ****************************************Medical History****************************************************** -->
<section >
	<div class="maain">
		@*<video autoplay loop  id="video" plays-inline>
			<source  src="~/Images/fg.jpg" type="video/mp4">
		</video>*@
		<img src="~/Doctor/Images/ll.jpg" no repeat id="video" />
		@*<div class="overrlay"></div>
		<div class="naavbar">
			<div class="logo">  <img src="~/Doctor/Images/logo.png" alt="" class="img-fluid" /> </div>
		</div>*@


		<div class="heading">
			<h1 class="head">Dr.<span>Lexandar James</span></h1>
			<br>
			<h3 class="sub">WELCOME TO OUR <span>Hospital</span></h3>
			
			
			
			<br>
			<br>
			<div class="bttns">
				<a class="btn1" asp-controller="HomeDoctor" asp-action="doctor">Work Start</a>

				<a class="btn2" asp-controller="HomeDoctor" asp-action="Close">Close work</a>
			</div>

		</div>
	</div>
    
</section>

Hospital-Management-System-By-Ibrahim/HMSproject/Views/HomeDoctor/doctor.cshtml
@* @model TModel *@

@{
	ViewData["Title"] = "Dashboard";
    Layout = "_LayoutDoctor";
}
    <style>
		.bg-1 {
			/*background-image: url("../Doctor/Images/22.jpg");*/
			/*background-color: red;*/
			background-size: cover;
			position: relative;
		}
	</style>


<!-- **firt page** -->
<section class="page-title bg-1">
	<div class="overlay"></div>
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<div class="block text-center">
					<span class="text-white"></span>
					<h1 class="text-capitalize">My Home</h1>
				</div>
				
			</div>
		</div>
	</div>
</section>
<!-- ********************************************************************************************** -->

<section class="information" id="About" style="background-color: whitesmoke;">
	<h2 class="t"> Doctor Information</h2>
	<div class="cards">

		<div class="c">
			<h2 class="title" style="color: white;">My Work</h2>
			@* <i class="fa-solid fa-laptop-code"> </i> *@
			<figure>
				<a asp-controller="Work" asp-action="Work" >
					<img src="~/Doctor/Images/syringe-solid.svg" height="100px" width="100px">
				</a>
               
				<p class="info" style="color: white; margin-left:7%;" >You can start your work.</p>
			</figure>
		</div>


		<div class="c">
			<h2 class="title" style="color: white;">My Profile</h2>


			@* <i class="fa-solid fa-laptop-code"> </i> *@
			<figure>
				<a asp-controller="Profile" asp-action="profile" >
					<img src="~/Doctor/Images/user-solid (2).svg" height="100px" width="100px">
				</a>
				<p class="info" style="color: white; margin-left:8%">You can see your profile.</p>
			</figure>


		</div>
	</div>
</section>


<a class="btn btn-slide-9" asp-controller="HomeDoctor" asp-action="Index" type="submit" style="background-color:black; margin-left: 85%; margin-top: 10%; color: white; ">Back &nbsp; <i style="color:white; margin:auto;" class="bi bi-arrow-bar-right"></i> </a>